
DROP TABLE IF EXISTS TA_MAT_MATERIAL_OBS;

CREATE TABLE TA_MAT_MATERIAL_OBS (
  I_ID SERIAL PRIMARY KEY,
  
  I_Status_01 integer DEFAULT NULL,
  I_Status_02 integer DEFAULT NULL,
  I_Status_03 integer DEFAULT NULL,
  I_Status_04 integer DEFAULT NULL,
  I_Status_05 integer DEFAULT NULL,
  
  I_Type_01 integer DEFAULT NULL,
  I_Type_02 integer DEFAULT NULL,
  I_Type_03 integer DEFAULT NULL,
  I_Type_04 integer DEFAULT NULL,
  I_Type_05 integer DEFAULT NULL,
  
  F_Val_01 DOUBLE PRECISION DEFAULT NULL ,
  F_Val_02 DOUBLE PRECISION DEFAULT NULL ,
  F_Val_03 DOUBLE PRECISION DEFAULT NULL ,
  F_Val_04 DOUBLE PRECISION DEFAULT NULL,
  F_Val_05 DOUBLE PRECISION DEFAULT NULL,
  
  T_Name_01 varchar(1000)  DEFAULT NULL,
  T_Name_02 varchar(1000)  DEFAULT NULL,
  T_Name_03 varchar(1000)  DEFAULT NULL,
  
  T_Code_01 varchar(500)  DEFAULT NULL,
  T_Code_02 varchar(500)  DEFAULT NULL,
  T_Code_03 varchar(500)  DEFAULT NULL,
  T_Code_04 varchar(500)  DEFAULT NULL,
  T_Code_05 varchar(500)  DEFAULT NULL,
  
  T_Info_01 text  DEFAULT NULL,
  T_Info_02 text  DEFAULT NULL,
  T_Info_03 text  DEFAULT NULL,
  T_Info_04 text  DEFAULT NULL,
  T_Info_05 text  DEFAULT NULL,
  T_Info_06 text  DEFAULT NULL,
  T_Info_07 text  DEFAULT NULL,
  T_Info_08 text  DEFAULT NULL,
  T_Info_09 text  DEFAULT NULL,
  T_Info_10 text  DEFAULT NULL,
  
  D_Date_01 timestamp DEFAULT NULL ,
  D_Date_02 timestamp DEFAULT NULL ,
  D_Date_03 timestamp DEFAULT NULL ,
  D_Date_04 timestamp DEFAULT NULL ,
  D_Date_05 timestamp DEFAULT NULL ,
  
  I_Aut_User_01 integer DEFAULT NULL,
  I_Aut_User_02 integer DEFAULT NULL,
  
  I_Per_Manager integer DEFAULT NULL,
  
  I_Per_Person_01 integer DEFAULT NULL ,
  I_Per_Person_02 integer DEFAULT NULL 
) ;

CREATE INDEX CONCURRENTLY idx_TMMAO_02 ON TA_MAT_MATERIAL_OBS USING btree(T_Name_01);
CREATE INDEX CONCURRENTLY idx_TMMAO_03 ON TA_MAT_MATERIAL_OBS USING btree(T_Name_02);

CREATE INDEX CONCURRENTLY idx_TMMAO_04 ON TA_MAT_MATERIAL_OBS USING btree(T_Code_01);
CREATE INDEX CONCURRENTLY idx_TMMAO_05 ON TA_MAT_MATERIAL_OBS USING btree(T_Code_02);
CREATE INDEX CONCURRENTLY idx_TMMAO_06 ON TA_MAT_MATERIAL_OBS USING btree(T_Code_03);
CREATE INDEX CONCURRENTLY idx_TMMAO_07 ON TA_MAT_MATERIAL_OBS USING btree(T_Code_04);
CREATE INDEX CONCURRENTLY idx_TMMAO_08 ON TA_MAT_MATERIAL_OBS USING btree(T_Code_05);

CREATE INDEX CONCURRENTLY idx_TMMAO_10 ON TA_MAT_MATERIAL_OBS USING btree(I_Per_Manager);
CREATE INDEX CONCURRENTLY idx_TMMAO_11 ON TA_MAT_MATERIAL_OBS USING btree(I_Per_Person_01);
CREATE INDEX CONCURRENTLY idx_TMMAO_12 ON TA_MAT_MATERIAL_OBS USING btree(I_Per_Person_02);

CREATE INDEX CONCURRENTLY idx_TMMAO_13 ON TA_MAT_MATERIAL_OBS USING btree(I_Type_01);
CREATE INDEX CONCURRENTLY idx_TMMAO_14 ON TA_MAT_MATERIAL_OBS USING btree(I_Type_02);

CREATE INDEX CONCURRENTLY idx_TMMAO_15 ON TA_MAT_MATERIAL_OBS USING btree(I_Status_01);
CREATE INDEX CONCURRENTLY idx_TMMAO_16 ON TA_MAT_MATERIAL_OBS USING btree(I_Status_02);

COMMENT on column TA_MAT_MATERIAL_OBS.I_Per_Person_01  		is 'per production';
COMMENT on column TA_MAT_MATERIAL_OBS.I_Per_Person_02  		is 'per other';
COMMENT on column TA_MAT_MATERIAL_OBS.D_Date_01 			is 'date creation';
COMMENT on column TA_MAT_MATERIAL_OBS.D_Date_02 			is 'date mod';
COMMENT on column TA_MAT_MATERIAL_OBS.D_Date_03 			is 'date begin';
COMMENT on column TA_MAT_MATERIAL_OBS.D_Date_04 			is 'date end';


